an:
  frontpage: 100
  main: 99
ar:
  frontpage: 100
  main: 53
be-BY:
  frontpage: 100
  main: 99
bg-BG:
  frontpage: 18
  main: 44
ca:
  frontpage: 81
  main: 83
cmn:
  frontpage: 0
  main: 31
cs:
  frontpage: 100
  main: 84
da:
  frontpage: 100
  main: 99
de:
  frontpage: 100
  main: 99
el:
  frontpage: 100
  main: 99
eo:
  frontpage: 100
  main: 97
es:
  frontpage: 100
  main: 100
fa-IR:
  frontpage: 100
  main: 13
fi:
  frontpage: 0
  main: 7
fr:
  frontpage: 100
  main: 99
ga-IE:
  frontpage: 37
  main: 47
gl:
  frontpage: 51
  main: 75
he:
  frontpage: 100
  main: 71
hr:
  frontpage: 100
  main: 50
hu:
  frontpage: 100
  main: 99
id:
  frontpage: 51
  main: 57
it:
  frontpage: 100
  main: 99
it-CH:
  frontpage: 0
  main: 0
ja:
  frontpage: 62
  main: 68
km:
  frontpage: 0
  main: 52
ko:
  frontpage: 97
  main: 61
lv:
  frontpage: 0
  main: 0
mi:
  frontpage: 2
  main: 0
mk:
  frontpage: 100
  main: 58
ml:
  frontpage: 0
  main: 55
nl-NL:
  frontpage: 100
  main: 99
pl:
  frontpage: 100
  main: 19
pt-BR:
  frontpage: 100
  main: 100
pt-PT:
  frontpage: 25
  main: 10
ro:
  frontpage: 100
  main: 99
ru:
  frontpage: 100
  main: 66
sk:
  frontpage: 100
  main: 99
sl:
  frontpage: 100
  main: 92
sr:
  frontpage: 100
  main: 99
sr-RS:
  frontpage: 100
  main: 99
sv:
  frontpage: 100
  main: 99
te:
  frontpage: 18
  main: 28
tr:
  frontpage: 100
  main: 99
uk:
  frontpage: 100
  main: 84
ur:
  frontpage: 0
  main: 0
ur-PK:
  frontpage: 0
  main: 0
vi:
  frontpage: 0
  main: 46
zh-TW:
  frontpage: 100
  main: 99
