an:
  frontpage: 51
  main_1_0: 17
  server: 46
ar:
  frontpage: 98
  main_1_0: 90
  server: 82
be-BY:
  frontpage: 100
  main_1_0: 24
  server: 86
bg-BG:
  frontpage: 9
  main_1_0: 13
  server: 11
ca:
  frontpage: 48
  main_1_0: 16
  server: 32
cmn:
  frontpage: 1
  main_1_0: 8
  server: 6
cs:
  frontpage: 75
  main_1_0: 55
  server: 58
da:
  frontpage: 51
  main_1_0: 26
  server: 46
de:
  frontpage: 98
  main_1_0: 81
  server: 79
el:
  frontpage: 98
  main_1_0: 40
  server: 68
en-BE:
  frontpage: 0
  main_1_0: 0
  server: 0
en-NL:
  frontpage: 0
  main_1_0: 0
  server: 0
en-US: {}
eo:
  frontpage: 51
  main_1_0: 21
  server: 46
es:
  frontpage: 100
  main_1_0: 100
  server: 100
es-AR:
  frontpage: 0
  main_1_0: 0
  server: 0
fa-IR:
  frontpage: 59
  main_1_0: 1
  server: 3
fi:
  frontpage: 98
  main_1_0: 12
  server: 7
fr:
  frontpage: 100
  main_1_0: 83
  server: 93
fr-BE:
  frontpage: 0
  main_1_0: 0
  server: 0
ga-IE:
  frontpage: 68
  main_1_0: 54
  server: 40
gl:
  frontpage: 28
  main_1_0: 13
  server: 19
he:
  frontpage: 54
  main_1_0: 11
  server: 21
he-IL: {}
hi:
  frontpage: 0
  main_1_0: 0
  server: 0
hi-IN: {}
hr:
  frontpage: 98
  main_1_0: 6
  server: 6
hu:
  frontpage: 72
  main_1_0: 27
  server: 57
id:
  frontpage: 28
  main_1_0: 14
  server: 27
io:
  frontpage: 7
  main_1_0: 0
  server: 1
it:
  frontpage: 100
  main_1_0: 70
  server: 77
it-CH:
  frontpage: 0
  main_1_0: 0
  server: 0
it-IT: {}
ja:
  frontpage: 71
  main_1_0: 18
  server: 34
km:
  frontpage: 7
  main_1_0: 13
  server: 25
ko:
  frontpage: 98
  main_1_0: 80
  server: 44
ko-KR: {}
lt:
  frontpage: 22
  main_1_0: 31
  server: 6
lv:
  frontpage: 0
  main_1_0: 0
  server: 0
mi:
  frontpage: 1
  main_1_0: 3
  server: 1
mk:
  frontpage: 51
  main_1_0: 12
  server: 29
ml:
  frontpage: 9
  main_1_0: 13
  server: 26
ml-IN:
  frontpage: 0
  main_1_0: 0
  server: 0
nb-NO:
  frontpage: 0
  main_1_0: 0
  server: 0
nl: {}
nl-NL:
  frontpage: 98
  main_1_0: 27
  server: 56
pl:
  frontpage: 98
  main_1_0: 50
  server: 22
pt-BR:
  frontpage: 100
  main_1_0: 100
  server: 100
pt-PT:
  frontpage: 16
  main_1_0: 0
  server: 3
ro:
  frontpage: 98
  main_1_0: 39
  server: 63
ru:
  frontpage: 59
  main_1_0: 22
  server: 17
ru-RU: {}
sk:
  frontpage: 51
  main_1_0: 17
  server: 46
sl:
  frontpage: 57
  main_1_0: 23
  server: 51
sr:
  frontpage: 98
  main_1_0: 81
  server: 79
sr-RS:
  frontpage: 68
  main_1_0: 22
  server: 76
sv:
  frontpage: 51
  main_1_0: 17
  server: 46
te:
  frontpage: 16
  main_1_0: 8
  server: 11
te-IN: {}
th: {}
th-TH:
  frontpage: 0
  main_1_0: 0
  server: 0
tr:
  frontpage: 98
  main_1_0: 86
  server: 82
uk:
  frontpage: 71
  main_1_0: 72
  server: 50
ur:
  frontpage: 0
  main_1_0: 0
  server: 0
ur-PK:
  frontpage: 0
  main_1_0: 0
  server: 0
vi:
  frontpage: 7
  main_1_0: 12
  server: 16
zh-TW:
  frontpage: 98
  main_1_0: 100
  server: 100
