an:
  frontpage: 52
  help docs: 8
  main: 87
  main_1_0: 26
ar:
  frontpage: 52
  help docs: 7
  main: 48
  main_1_0: 14
be-BY:
  frontpage: 58
  help docs: 10
  main: 94
  main_1_0: 29
bg-BG:
  frontpage: 9
  help docs: 2
  main: 41
  main_1_0: 17
ca:
  frontpage: 49
  help docs: 7
  main: 73
  main_1_0: 24
cmn:
  frontpage: 1
  help docs: 1
  main: 29
  main_1_0: 11
cs:
  frontpage: 76
  help docs: 44
  main: 79
  main_1_0: 61
da:
  frontpage: 52
  help docs: 11
  main: 87
  main_1_0: 38
de:
  frontpage: 100
  help docs: 64
  main: 100
  main_1_0: 99
el:
  frontpage: 78
  help docs: 42
  main: 94
  main_1_0: 33
en-BE:
  frontpage: 0
  help docs: 0
  main: 0
  main_1_0: 0
en-NL:
  frontpage: 0
  help docs: 0
  main: 0
  main_1_0: 0
eo:
  frontpage: 52
  help docs: 8
  main: 85
  main_1_0: 25
es:
  frontpage: 100
  help docs: 87
  main: 97
  main_1_0: 85
fa-IR:
  frontpage: 60
  help docs: 41
  main: 14
  main_1_0: 2
fi:
  frontpage: 0
  help docs: 0
  main: 6
  main_1_0: 0
fr:
  frontpage: 60
  help docs: 29
  main: 96
  main_1_0: 38
ga-IE:
  frontpage: 69
  help docs: 9
  main: 60
  main_1_0: 81
gl:
  frontpage: 29
  help docs: 8
  main: 67
  main_1_0: 19
he:
  frontpage: 55
  help docs: 8
  main: 63
  main_1_0: 16
he-IL: {}
hi:
  frontpage: 0
  help docs: 0
  main: 1
  main_1_0: 0
hr:
  frontpage: 100
  help docs: 14
  main: 46
  main_1_0: 8
hu:
  frontpage: 63
  help docs: 74
  main: 95
  main_1_0: 36
id:
  frontpage: 29
  help docs: 2
  main: 53
  main_1_0: 21
it:
  frontpage: 60
  help docs: 41
  main: 89
  main_1_0: 87
it-CH:
  frontpage: 0
  help docs: 0
  main: 0
  main_1_0: 0
it-IT: {}
ja:
  frontpage: 49
  help docs: 4
  main: 61
  main_1_0: 22
km:
  frontpage: 7
  help docs: 2
  main: 48
  main_1_0: 19
ko:
  frontpage: 52
  help docs: 3
  main: 55
  main_1_0: 19
lt:
  frontpage: 23
  help docs: 9
  main: 9
  main_1_0: 45
lv:
  frontpage: 0
  help docs: 0
  main: 0
  main_1_0: 0
mi:
  frontpage: 1
  help docs: 0
  main: 4
  main_1_0: 5
mk:
  frontpage: 52
  help docs: 3
  main: 53
  main_1_0: 17
ml:
  frontpage: 9
  help docs: 3
  main: 51
  main_1_0: 19
ml-IN:
  frontpage: 0
  help docs: 0
  main: 0
  main_1_0: 0
nl: {}
nl-NL:
  frontpage: 100
  help docs: 47
  main: 92
  main_1_0: 38
pl:
  frontpage: 100
  help docs: 56
  main: 58
  main_1_0: 83
pt-BR:
  frontpage: 100
  help docs: 100
  main: 100
  main_1_0: 100
pt-PT:
  frontpage: 16
  help docs: 0
  main: 9
  main_1_0: 0
ro:
  frontpage: 100
  help docs: 53
  main: 97
  main_1_0: 29
ru:
  frontpage: 60
  help docs: 10
  main: 64
  main_1_0: 32
sk:
  frontpage: 52
  help docs: 8
  main: 87
  main_1_0: 26
sl:
  frontpage: 58
  help docs: 10
  main: 90
  main_1_0: 34
sr:
  frontpage: 100
  help docs: 11
  main: 99
  main_1_0: 54
sr-RS:
  frontpage: 58
  help docs: 10
  main: 93
  main_1_0: 28
sv:
  frontpage: 52
  help docs: 8
  main: 86
  main_1_0: 25
te:
  frontpage: 15
  help docs: 2
  main: 28
  main_1_0: 12
tr:
  frontpage: 52
  help docs: 10
  main: 87
  main_1_0: 36
uk:
  frontpage: 64
  help docs: 8
  main: 74
  main_1_0: 24
ur:
  frontpage: 0
  help docs: 0
  main: 0
  main_1_0: 0
ur-PK:
  frontpage: 0
  help docs: 0
  main: 0
  main_1_0: 0
vi:
  frontpage: 7
  help docs: 2
  main: 43
  main_1_0: 17
zh-TW:
  frontpage: 100
  help docs: 46
  main: 100
  main_1_0: 100
