an:
  main_1_0: 17
  marketing: 0
  server: 45
ar:
  main_1_0: 86
  marketing: 0
  server: 79
be-BY:
  main_1_0: 23
  marketing: 0
  server: 83
bg-BG:
  main_1_0: 12
  marketing: 0
  server: 11
ca:
  main_1_0: 16
  marketing: 0
  server: 31
cmn:
  main_1_0: 7
  marketing: 0
  server: 5
cs:
  main_1_0: 53
  marketing: 0
  server: 55
da:
  main_1_0: 25
  marketing: 0
  server: 45
de:
  main_1_0: 99
  marketing: 0
  server: 86
el:
  main_1_0: 39
  marketing: 0
  server: 67
en-BE:
  main_1_0: 0
  marketing: 0
  server: 0
en-NL:
  main_1_0: 0
  marketing: 0
  server: 0
en-US: {}
eo:
  main_1_0: 21
  marketing: 0
  server: 45
es:
  main_1_0: 99
  marketing: 100
  server: 100
es-AR:
  main_1_0: 0
  marketing: 0
  server: 0
fa-IR:
  main_1_0: 1
  marketing: 0
  server: 3
fi:
  main_1_0: 11
  marketing: 0
  server: 7
fr:
  main_1_0: 98
  marketing: 0
  server: 97
fr-BE:
  main_1_0: 0
  marketing: 0
  server: 0
ga-IE:
  main_1_0: 64
  marketing: 0
  server: 38
gl:
  main_1_0: 13
  marketing: 0
  server: 18
he:
  main_1_0: 11
  marketing: 0
  server: 20
he-IL: {}
hi:
  main_1_0: 0
  marketing: 0
  server: 0
hi-IN: {}
hr:
  main_1_0: 5
  marketing: 0
  server: 5
hu:
  main_1_0: 31
  marketing: 0
  server: 55
id:
  main_1_0: 14
  marketing: 0
  server: 26
io:
  main_1_0: 0
  marketing: 0
  server: 1
it:
  main_1_0: 67
  marketing: 0
  server: 74
it-CH:
  main_1_0: 0
  marketing: 0
  server: 0
it-IT: {}
ja:
  main_1_0: 17
  marketing: 0
  server: 34
km:
  main_1_0: 12
  marketing: 0
  server: 25
ko:
  main_1_0: 78
  marketing: 0
  server: 41
ko-KR: {}
lt:
  main_1_0: 29
  marketing: 0
  server: 6
lv:
  main_1_0: 0
  marketing: 0
  server: 0
mi:
  main_1_0: 3
  marketing: 0
  server: 1
mk:
  main_1_0: 11
  marketing: 0
  server: 28
ml:
  main_1_0: 13
  marketing: 0
  server: 25
ml-IN:
  main_1_0: 0
  marketing: 0
  server: 0
nb-NO:
  main_1_0: 0
  marketing: 0
  server: 0
nl: {}
nl-NL:
  main_1_0: 26
  marketing: 0
  server: 55
pl:
  main_1_0: 48
  marketing: 0
  server: 22
pt-BR:
  main_1_0: 99
  marketing: 0
  server: 100
pt-PT:
  main_1_0: 0
  marketing: 0
  server: 2
ro:
  main_1_0: 37
  marketing: 0
  server: 61
ru:
  main_1_0: 21
  marketing: 0
  server: 16
ru-RU: {}
sk:
  main_1_0: 17
  marketing: 0
  server: 45
sl:
  main_1_0: 22
  marketing: 0
  server: 50
sr:
  main_1_0: 83
  marketing: 0
  server: 91
sr-RS:
  main_1_0: 21
  marketing: 0
  server: 73
sv:
  main_1_0: 17
  marketing: 0
  server: 45
te:
  main_1_0: 8
  marketing: 0
  server: 11
te-IN: {}
th: {}
th-TH:
  main_1_0: 0
  marketing: 0
  server: 0
tr:
  main_1_0: 82
  marketing: 0
  server: 79
uk:
  main_1_0: 69
  marketing: 0
  server: 47
ur:
  main_1_0: 0
  marketing: 0
  server: 0
ur-PK:
  main_1_0: 0
  marketing: 0
  server: 0
vi:
  main_1_0: 12
  marketing: 0
  server: 16
zh-TW:
  main_1_0: 100
  marketing: 100
  server: 100
