af:
  main_1_0: 0
  marketing: 0
  server: 0
an:
  main_1_0: 14
  marketing: 0
  server: 30
ar:
  main_1_0: 68
  marketing: 0
  server: 51
be-BY:
  main_1_0: 18
  marketing: 0
  server: 54
bg-BG:
  main_1_0: 10
  marketing: 0
  server: 8
ca:
  main_1_0: 77
  marketing: 62
  server: 55
cmn:
  main_1_0: 6
  marketing: 0
  server: 3
cs:
  main_1_0: 49
  marketing: 2
  server: 39
da:
  main_1_0: 21
  marketing: 0
  server: 30
de:
  main_1_0: 78
  marketing: 0
  server: 54
el:
  main_1_0: 32
  marketing: 0
  server: 44
en-BE:
  main_1_0: 0
  marketing: 0
  server: 0
en-NL:
  main_1_0: 0
  marketing: 0
  server: 0
en-US: {}
eo:
  main_1_0: 17
  marketing: 0
  server: 30
es:
  main_1_0: 96
  marketing: 100
  server: 99
es-AR:
  main_1_0: 0
  marketing: 0
  server: 0
fa-IR:
  main_1_0: 1
  marketing: 0
  server: 2
fi:
  main_1_0: 10
  marketing: 0
  server: 5
fr:
  main_1_0: 99
  marketing: 100
  server: 100
fr-BE:
  main_1_0: 0
  marketing: 0
  server: 0
ga-IE:
  main_1_0: 65
  marketing: 2
  server: 30
gl:
  main_1_0: 10
  marketing: 0
  server: 13
he:
  main_1_0: 9
  marketing: 0
  server: 15
he-IL: {}
hi:
  main_1_0: 0
  marketing: 0
  server: 0
hi-IN: {}
hr:
  main_1_0: 5
  marketing: 0
  server: 4
hu:
  main_1_0: 37
  marketing: 0
  server: 37
id:
  main_1_0: 12
  marketing: 0
  server: 17
io:
  main_1_0: 0
  marketing: 0
  server: 0
it:
  main_1_0: 53
  marketing: 0
  server: 48
it-CH:
  main_1_0: 0
  marketing: 0
  server: 0
it-IT: {}
ja:
  main_1_0: 15
  marketing: 0
  server: 22
km:
  main_1_0: 10
  marketing: 0
  server: 16
ko:
  main_1_0: 62
  marketing: 0
  server: 27
ko-KR: {}
lt:
  main_1_0: 24
  marketing: 0
  server: 6
lv:
  main_1_0: 0
  marketing: 0
  server: 0
mi:
  main_1_0: 8
  marketing: 1
  server: 1
mk:
  main_1_0: 10
  marketing: 0
  server: 20
ml:
  main_1_0: 11
  marketing: 0
  server: 16
ml-IN:
  main_1_0: 0
  marketing: 0
  server: 0
nb-NO:
  main_1_0: 0
  marketing: 0
  server: 0
nl: {}
nl-NL:
  main_1_0: 28
  marketing: 17
  server: 54
pl:
  main_1_0: 39
  marketing: 0
  server: 16
pt-BR:
  main_1_0: 100
  marketing: 100
  server: 100
pt-PT:
  main_1_0: 0
  marketing: 0
  server: 2
ro:
  main_1_0: 31
  marketing: 0
  server: 42
ru:
  main_1_0: 36
  marketing: 2
  server: 13
ru-RU: {}
sk:
  main_1_0: 14
  marketing: 0
  server: 30
sl:
  main_1_0: 19
  marketing: 0
  server: 33
sr:
  main_1_0: 81
  marketing: 81
  server: 86
sr-RS:
  main_1_0: 27
  marketing: 0
  server: 48
sv:
  main_1_0: 23
  marketing: 62
  server: 32
te:
  main_1_0: 7
  marketing: 0
  server: 9
te-IN: {}
th: {}
th-TH:
  main_1_0: 0
  marketing: 0
  server: 0
tr:
  main_1_0: 65
  marketing: 0
  server: 51
uk:
  main_1_0: 83
  marketing: 4
  server: 32
ur:
  main_1_0: 0
  marketing: 0
  server: 0
ur-PK:
  main_1_0: 0
  marketing: 0
  server: 0
vi:
  main_1_0: 10
  marketing: 0
  server: 11
zh-TW:
  main_1_0: 100
  marketing: 100
  server: 99
