an:
  frontpage: 51
  main_1_0: 18
  server: 48
ar:
  frontpage: 98
  main_1_0: 92
  server: 85
be-BY:
  frontpage: 100
  main_1_0: 24
  server: 89
bg-BG:
  frontpage: 9
  main_1_0: 13
  server: 12
ca:
  frontpage: 48
  main_1_0: 17
  server: 33
cmn:
  frontpage: 1
  main_1_0: 8
  server: 6
cs:
  frontpage: 75
  main_1_0: 56
  server: 60
da:
  frontpage: 51
  main_1_0: 27
  server: 48
de:
  frontpage: 98
  main_1_0: 83
  server: 82
el:
  frontpage: 98
  main_1_0: 42
  server: 71
en-BE:
  frontpage: 0
  main_1_0: 0
  server: 0
en-NL:
  frontpage: 0
  main_1_0: 0
  server: 0
en-US: {}
eo:
  frontpage: 51
  main_1_0: 22
  server: 48
es:
  frontpage: 98
  main_1_0: 100
  server: 99
es-AR:
  frontpage: 0
  main_1_0: 0
  server: 0
fa-IR:
  frontpage: 59
  main_1_0: 1
  server: 3
fi:
  frontpage: 98
  main_1_0: 12
  server: 7
fr:
  frontpage: 98
  main_1_0: 84
  server: 82
fr-BE:
  frontpage: 0
  main_1_0: 0
  server: 0
ga-IE:
  frontpage: 68
  main_1_0: 55
  server: 42
gl:
  frontpage: 28
  main_1_0: 13
  server: 19
he:
  frontpage: 54
  main_1_0: 11
  server: 22
he-IL: {}
hi:
  frontpage: 0
  main_1_0: 0
  server: 0
hi-IN: {}
hr:
  frontpage: 98
  main_1_0: 6
  server: 6
hu:
  frontpage: 72
  main_1_0: 28
  server: 59
id:
  frontpage: 28
  main_1_0: 14
  server: 28
io:
  frontpage: 7
  main_1_0: 0
  server: 1
it:
  frontpage: 100
  main_1_0: 71
  server: 80
it-CH:
  frontpage: 0
  main_1_0: 0
  server: 0
it-IT: {}
ja:
  frontpage: 71
  main_1_0: 18
  server: 36
km:
  frontpage: 7
  main_1_0: 13
  server: 26
ko:
  frontpage: 98
  main_1_0: 82
  server: 45
ko-KR: {}
lt:
  frontpage: 22
  main_1_0: 31
  server: 7
lv:
  frontpage: 0
  main_1_0: 0
  server: 0
mi:
  frontpage: 1
  main_1_0: 3
  server: 1
mk:
  frontpage: 51
  main_1_0: 12
  server: 30
ml:
  frontpage: 9
  main_1_0: 13
  server: 27
ml-IN:
  frontpage: 0
  main_1_0: 0
  server: 0
nl: {}
nl-NL:
  frontpage: 98
  main_1_0: 28
  server: 58
pl:
  frontpage: 98
  main_1_0: 51
  server: 23
pt-BR:
  frontpage: 98
  main_1_0: 92
  server: 94
pt-PT:
  frontpage: 16
  main_1_0: 0
  server: 3
ro:
  frontpage: 98
  main_1_0: 39
  server: 65
ru:
  frontpage: 59
  main_1_0: 23
  server: 17
ru-RU: {}
sk:
  frontpage: 51
  main_1_0: 18
  server: 48
sl:
  frontpage: 57
  main_1_0: 23
  server: 53
sr:
  frontpage: 98
  main_1_0: 83
  server: 82
sr-RS:
  frontpage: 68
  main_1_0: 22
  server: 79
sv:
  frontpage: 51
  main_1_0: 18
  server: 48
te:
  frontpage: 15
  main_1_0: 8
  server: 12
te-IN: {}
th: {}
th-TH:
  frontpage: 0
  main_1_0: 0
  server: 0
tr:
  frontpage: 98
  main_1_0: 88
  server: 85
uk:
  frontpage: 71
  main_1_0: 73
  server: 52
ur:
  frontpage: 0
  main_1_0: 0
  server: 0
ur-PK:
  frontpage: 0
  main_1_0: 0
  server: 0
vi:
  frontpage: 7
  main_1_0: 12
  server: 17
zh-TW:
  frontpage: 98
  main_1_0: 92
  server: 86
