an:
  frontpage: 52
  main_1_0: 18
  server: 53
ar:
  frontpage: 100
  main_1_0: 99
  server: 99
be-BY:
  frontpage: 58
  main_1_0: 23
  server: 68
bg-BG:
  frontpage: 9
  main_1_0: 13
  server: 13
ca:
  frontpage: 49
  main_1_0: 17
  server: 37
cmn:
  frontpage: 1
  main_1_0: 8
  server: 7
cs:
  frontpage: 76
  main_1_0: 57
  server: 68
da:
  frontpage: 52
  main_1_0: 27
  server: 53
de:
  frontpage: 100
  main_1_0: 90
  server: 95
el:
  frontpage: 100
  main_1_0: 47
  server: 80
en-BE:
  frontpage: 0
  main_1_0: 0
  server: 0
en-NL:
  frontpage: 0
  main_1_0: 0
  server: 0
en-US: {}
eo:
  frontpage: 52
  main_1_0: 23
  server: 53
es:
  frontpage: 100
  main_1_0: 94
  server: 99
es-AR:
  frontpage: 0
  main_1_0: 0
  server: 0
fa-IR:
  frontpage: 60
  main_1_0: 1
  server: 4
fi:
  frontpage: 0
  main_1_0: 0
  server: 0
fr:
  frontpage: 100
  main_1_0: 92
  server: 95
fr-BE:
  frontpage: 0
  main_1_0: 0
  server: 0
ga-IE:
  frontpage: 69
  main_1_0: 57
  server: 46
gl:
  frontpage: 29
  main_1_0: 13
  server: 21
he:
  frontpage: 55
  main_1_0: 11
  server: 24
he-IL: {}
hi:
  frontpage: 0
  main_1_0: 0
  server: 0
hi-IN: {}
hr:
  frontpage: 100
  main_1_0: 6
  server: 7
hu:
  frontpage: 73
  main_1_0: 29
  server: 65
id:
  frontpage: 29
  main_1_0: 15
  server: 31
io:
  frontpage: 7
  main_1_0: 0
  server: 1
it:
  frontpage: 100
  main_1_0: 78
  server: 92
it-CH:
  frontpage: 0
  main_1_0: 0
  server: 0
it-IT: {}
ja:
  frontpage: 72
  main_1_0: 19
  server: 40
km:
  frontpage: 7
  main_1_0: 13
  server: 29
ko:
  frontpage: 100
  main_1_0: 90
  server: 53
ko-KR: {}
lt:
  frontpage: 23
  main_1_0: 31
  server: 7
lv:
  frontpage: 0
  main_1_0: 0
  server: 0
mi:
  frontpage: 1
  main_1_0: 3
  server: 2
mk:
  frontpage: 52
  main_1_0: 12
  server: 34
ml:
  frontpage: 9
  main_1_0: 14
  server: 30
ml-IN:
  frontpage: 0
  main_1_0: 0
  server: 0
nl: {}
nl-NL:
  frontpage: 100
  main_1_0: 29
  server: 65
pl:
  frontpage: 100
  main_1_0: 53
  server: 26
pt-BR:
  frontpage: 100
  main_1_0: 100
  server: 100
pt-PT:
  frontpage: 16
  main_1_0: 0
  server: 3
ro:
  frontpage: 100
  main_1_0: 45
  server: 73
ru:
  frontpage: 60
  main_1_0: 23
  server: 19
ru-RU: {}
sk:
  frontpage: 52
  main_1_0: 18
  server: 53
sl:
  frontpage: 58
  main_1_0: 24
  server: 59
sr:
  frontpage: 100
  main_1_0: 90
  server: 94
sr-RS:
  frontpage: 69
  main_1_0: 23
  server: 91
sv:
  frontpage: 52
  main_1_0: 18
  server: 53
te:
  frontpage: 15
  main_1_0: 8
  server: 13
te-IN: {}
th: {}
th-TH:
  frontpage: 0
  main_1_0: 0
  server: 0
tr:
  frontpage: 100
  main_1_0: 95
  server: 98
uk:
  frontpage: 72
  main_1_0: 81
  server: 60
ur:
  frontpage: 0
  main_1_0: 0
  server: 0
ur-PK:
  frontpage: 0
  main_1_0: 0
  server: 0
vi:
  frontpage: 7
  main_1_0: 13
  server: 19
zh-TW:
  frontpage: 100
  main_1_0: 100
  server: 100
