an:
  main_1_0: 16
  marketing: 0
  server: 29
ar:
  main_1_0: 78
  marketing: 0
  server: 54
be-BY:
  main_1_0: 21
  marketing: 0
  server: 55
bg-BG:
  main_1_0: 12
  marketing: 0
  server: 8
ca:
  main_1_0: 89
  marketing: 63
  server: 55
cmn:
  main_1_0: 7
  marketing: 0
  server: 3
cs:
  main_1_0: 54
  marketing: 1
  server: 38
da:
  main_1_0: 24
  marketing: 0
  server: 29
de:
  main_1_0: 90
  marketing: 0
  server: 57
el:
  main_1_0: 36
  marketing: 0
  server: 45
en-BE:
  main_1_0: 0
  marketing: 0
  server: 0
en-NL:
  main_1_0: 0
  marketing: 0
  server: 0
en-US: {}
eo:
  main_1_0: 20
  marketing: 0
  server: 29
es:
  main_1_0: 99
  marketing: 82
  server: 100
es-AR:
  main_1_0: 0
  marketing: 0
  server: 0
fa-IR:
  main_1_0: 1
  marketing: 0
  server: 2
fi:
  main_1_0: 10
  marketing: 0
  server: 5
fr:
  main_1_0: 91
  marketing: 0
  server: 70
fr-BE:
  main_1_0: 0
  marketing: 0
  server: 0
ga-IE:
  main_1_0: 62
  marketing: 0
  server: 29
gl:
  main_1_0: 12
  marketing: 0
  server: 13
he:
  main_1_0: 10
  marketing: 0
  server: 15
he-IL: {}
hi:
  main_1_0: 0
  marketing: 0
  server: 0
hi-IN: {}
hr:
  main_1_0: 5
  marketing: 0
  server: 4
hu:
  main_1_0: 41
  marketing: 0
  server: 37
id:
  main_1_0: 13
  marketing: 0
  server: 17
io:
  main_1_0: 0
  marketing: 0
  server: 0
it:
  main_1_0: 61
  marketing: 0
  server: 50
it-CH:
  main_1_0: 0
  marketing: 0
  server: 0
it-IT: {}
ja:
  main_1_0: 17
  marketing: 0
  server: 22
km:
  main_1_0: 12
  marketing: 0
  server: 16
ko:
  main_1_0: 71
  marketing: 0
  server: 27
ko-KR: {}
lt:
  main_1_0: 28
  marketing: 0
  server: 6
lv:
  main_1_0: 0
  marketing: 0
  server: 0
mi:
  main_1_0: 3
  marketing: 0
  server: 1
mk:
  main_1_0: 11
  marketing: 0
  server: 19
ml:
  main_1_0: 12
  marketing: 0
  server: 16
ml-IN:
  main_1_0: 0
  marketing: 0
  server: 0
nb-NO:
  main_1_0: 0
  marketing: 0
  server: 0
nl: {}
nl-NL:
  main_1_0: 31
  marketing: 18
  server: 54
pl:
  main_1_0: 45
  marketing: 0
  server: 16
pt-BR:
  main_1_0: 90
  marketing: 0
  server: 66
pt-PT:
  main_1_0: 0
  marketing: 0
  server: 2
ro:
  main_1_0: 34
  marketing: 0
  server: 42
ru:
  main_1_0: 20
  marketing: 0
  server: 11
ru-RU: {}
sk:
  main_1_0: 16
  marketing: 0
  server: 29
sl:
  main_1_0: 21
  marketing: 0
  server: 33
sr:
  main_1_0: 93
  marketing: 82
  server: 89
sr-RS:
  main_1_0: 30
  marketing: 0
  server: 50
sv:
  main_1_0: 16
  marketing: 0
  server: 29
te:
  main_1_0: 7
  marketing: 0
  server: 9
te-IN: {}
th: {}
th-TH:
  main_1_0: 0
  marketing: 0
  server: 0
tr:
  main_1_0: 75
  marketing: 0
  server: 54
uk:
  main_1_0: 62
  marketing: 0
  server: 31
ur:
  main_1_0: 0
  marketing: 0
  server: 0
ur-PK:
  main_1_0: 0
  marketing: 0
  server: 0
vi:
  main_1_0: 11
  marketing: 0
  server: 10
zh-TW:
  main_1_0: 99
  marketing: 100
  server: 99
