RecordStore = require 'shared/interfaces/record_store.coffee'

records = new RecordStore()

records.addRecordsInterface require('shared/interfaces/comment_records_interface.coffee')
records.addRecordsInterface require('shared/interfaces/discussion_records_interface.coffee')
records.addRecordsInterface require('shared/interfaces/event_records_interface.coffee')
records.addRecordsInterface require('shared/interfaces/group_records_interface.coffee')
records.addRecordsInterface require('shared/interfaces/membership_records_interface.coffee')
records.addRecordsInterface require('shared/interfaces/membershipRequest_records_interface.coffee')
records.addRecordsInterface require('shared/interfaces/notification_records_interface.coffee')
records.addRecordsInterface require('shared/interfaces/user_records_interface.coffee')
records.addRecordsInterface require('shared/interfaces/searchResult_records_interface.coffee')
records.addRecordsInterface require('shared/interfaces/contact_records_interface.coffee')
records.addRecordsInterface require('shared/interfaces/invitation_records_interface.coffee')
records.addRecordsInterface require('shared/interfaces/invitationForm_records_interface.coffee')
records.addRecordsInterface require('shared/interfaces/version_records_interface.coffee')
records.addRecordsInterface require('shared/interfaces/draft_records_interface.coffee')
records.addRecordsInterface require('shared/interfaces/translation_records_interface.coffee')
records.addRecordsInterface require('shared/interfaces/oauthApplication_records_interface.coffee')
records.addRecordsInterface require('shared/interfaces/session_records_interface.coffee')
records.addRecordsInterface require('shared/interfaces/registration_records_interface.coffee')
records.addRecordsInterface require('shared/interfaces/poll_records_interface.coffee')
records.addRecordsInterface require('shared/interfaces/pollOption_records_interface.coffee')
records.addRecordsInterface require('shared/interfaces/stance_records_interface.coffee')
records.addRecordsInterface require('shared/interfaces/stanceChoice_records_interface.coffee')
records.addRecordsInterface require('shared/interfaces/outcome_records_interface.coffee')
records.addRecordsInterface require('shared/interfaces/pollDidNotVote_records_interface.coffee')
records.addRecordsInterface require('shared/interfaces/identity_records_interface.coffee')
records.addRecordsInterface require('shared/interfaces/contactMessage_records_interface.coffee')
records.addRecordsInterface require('shared/interfaces/groupIdentity_records_interface.coffee')
records.addRecordsInterface require('shared/interfaces/reaction_records_interface.coffee')
records.addRecordsInterface require('shared/interfaces/contactRequest_records_interface.coffee')
records.addRecordsInterface require('shared/interfaces/document_records_interface.coffee')

module.exports = records
