class PollTemplateSerializer < ActiveModel::Serializer
  embed :ids, include: true
  
  has_one :group, serializer: GroupSerializer, root: :groups

  attributes :id,
             :key,
             :group_id,
             :position,
             :author_id,
             :poll_type,
             :process_name,
             :process_subtitle,
             :process_introduction,
             :process_introduction_format,
             :tags,
             :title,
             :title_placeholder,
             :details,
             :details_format,
             :anonymous,
             :specified_voters_only,
             :notify_on_closing_soon,
             :content_locale,
             :shuffle_options,
             :hide_results,
             :chart_type,
             :min_score,
             :max_score,
             :minimum_stance_choices,
             :maximum_stance_choices,
             :dots_per_person,
             :reason_prompt,
             :poll_options,
             :poll_option_name_format,
             :stance_reason_required,
             :limit_reason_length,
             :default_duration_in_days,
             :agree_target,
             :created_at,
             :updated_at,
             :discarded_at,
             :outcome_statement,
             :outcome_statement_format,
             :outcome_review_due_in_days
end
