development:
  adapter: solid_cable
  polling_interval: 0.1.seconds
  message_retention: 1.day

test:
  adapter: solid_cable
  polling_interval: 0.1.seconds
  message_retention: 1.day

production:
  adapter: solid_cable
  polling_interval: 0.1.seconds
  message_retention: 1.day
