poll:
  - "#70C9F8"
  - "#C8E56E"
  - "#D38FE1"
  - "#999FDE"
  - "#FA8295"
  - "#97D298"
  - "#C19A93"
  - "#F68AC6"
  - "#70C9F8"
  - "#C8E56E"
  - "#D38FE1"
  - "#999FDE"
  - "#FA8295"
  - "#97D298"
  - "#C19A93"
  - "#F68AC6"
  - "#70C9F8"
  - "#C8E56E"
  - "#D38FE1"
  - "#999FDE"
  - "#FA8295"
  - "#97D298"
  - "#C19A93"
  - "#F68AC6"
proposal:
  - "#22B866"
  - "#F5C401"
  - "#F05252"
  - "#595959"
count:
  - "#1CA9F4"
  - "#DDDDDD"
missing: "#FF0000"
