service: loomio
image: loomio/loomio_com
builder:
  args:
    LOOMIOCOM: 1
  multiarch: false

servers:
  web:
    hosts:
      - 165.227.76.125
    labels:
      traefik.http.routers.loomio-web.rule: PathPrefix(`/`)
      traefik.http.routers.loomio-web.entrypoints: web
      traefik.http.routers.loomio-web-secure.rule: Host(`www.loomio.com`)
      traefik.http.routers.loomio-web-secure.tls: true
      traefik.http.routers.loomio-web-secure.entrypoints: websecure
      # traefik.http.routers.loomio-web.rule: Path(`/`)
      # traefik.http.routers.loomio-web-secure.rule: Path(`/`)
      # traefik.http.routers.loomio-web-secure.tls.certresolver: letsencrypt
  job:
    hosts:
      - 159.89.42.168
    cmd: bundle exec sidekiq    

  cron:
    hosts:
      - 159.89.42.168
    cmd:
      bash -c "cat config/crontab | crontab - && cron -f"

registry:
  server: ghcr.io
  username: robguthrie
  password:
    - GH_PAT

env:
  secret:
    - AWS_ACCESS_KEY_ID
    - AWS_SECRET_ACCESS_KEY
    - CHARGIFY_API_KEY
    - CHARGIFY_APP_NAME
    - CHARGIFY_SITE_KEY
    - DATABASE_URL
    - DEVISE_SECRET
    - GOOGLE_APP_KEY
    - GOOGLE_APP_SECRET
    - GOOGLE_CLOUD_KEY
    - REDIS_CACHE_URL
    - REDIS_QUEUE_URL
    - RECAPTCHA_APP_KEY
    - RECAPTCHA_SECRET_KEY
    - SECRET_KEY_BASE
    - SENTRY_PUBLIC_DSN
    - SMTP_PASSWORD
    - SMTP_USERNAME
    - TRANSLATE_CREDENTIALS

  clear:
    ALLOW_ROBOTS: 1
    # ASSUME_SSL: 1
    AWS_BUCKET: loomio-uploads
    AWS_REGION: us-east-1
    CANONICAL_HOST: www.loomio.com
    CHANNELS_URI: 'wss://channels.loomio.com'
    ERROR_PAGE_URL: 'https://help.loomio.com/en/error'
    MAINTENANCE_PAGE_URL: 'https://help.loomio.com/en/maintenance'
    EXPLORE_MIN_MEMBERS: 4
    EXPLORE_MIN_THREADS: 2
    EXPLORE_REQUIRE_SUBSCRIPTION: 1
    FB_APP_ID_META: 457851034283863
    FEATURES_DEMO_GROUPS: 1
    FEATURES_SHOW_CONTACT: 1
    FEATURES_SHOW_CONTACT_CONSENT: 1
    FEATURES_SUBSCRIPTIONS: 1
    FEATURES_TRIALS: 1
    FORCE_SSL: 1
    GOOGLE_SITE_VERIFICATION: VBjE1ew0T5SvIIaVInuq-fkL4DkBKt3yVm0rptVREhc
    HELPER_BOT_EMAIL: 'contact@loomio.com'
    MALLOC_ARENA_MAX: 2
    MAX_PENDING_INVITATIONS: 10000
    MAX_THREADS: 10
    MIN_THREADS: 10
    NEWSLETTER_ENABLED: 1
    OLD_REPLY_HOSTNAME: reply.loomio.org
    PAID_INVITATIONS_RATE_LIMIT: 50000
    PLAUSIBLE_SITE: 'loomio.org,all.loomio.com'
    PLAUSIBLE_SRC: 'https://measure.loomio.com/js/script.js'
    PRIVACY_URL: 'https://help.loomio.com/en/policy/privacy'
    PUMA_WORKERS: 4
    RACK_ATTACK_RATE_MULTPLIER: 3
    RACK_TIMEOUT_SERVICE_TIMEOUT: 30
    RAILS_ENV: production
    RAILS_LOG_LEVEL: info
    # REDIRECT_TO_CANONICAL_HOST: 1
    REPLY_HOSTNAME: reply.loomio.com
    SENTRY_SAMPLE_RATE: 0.1
    SMTP_AUTH: plain
    SMTP_DOMAIN: loomio.com
    SMTP_PORT: 587
    SMTP_SERVER: email-smtp.us-east-1.amazonaws.com
    SPAM_REGEX: '(flipssl\\.com|zoofood\\.org|w3boats\\.com|revutap\\.com|slowimo\\.com|relumyx\\.com|fineoak\\.org|diide\\.com|gusronk\\.com|appnox\\.com|akxpert\\.com|patmui\\.com|xhypm\\.com|5y5u\\.com|boldhut\\.com|botfed\\.com|fineloans\\.org|netjook\\.com|aramidth\\.com|kindbest\\.com|bsmitao\\.com|astarmax\\.com|irahada\\.com|naymeo\\.com|ichkoch\\.com|onzmail\\.com|seacob\\.com|fineloans\\.org|bombaya\\.com|astarmax\\.com|asfalio\\.com|wifimaple\\.com|whyflkj\\.com|ddwfzp\\.com|sejkt\\.com)'
    SUPPORT_EMAIL: 'contact@loomio.com'
    TERMS_URL: 'https://help.loomio.com/en/policy/terms'
    TRIAL_DAYS: 7
    TRIAL_INVITATIONS_RATE_LIMIT: 150
    USE_RACK_ATTACK: 1

accessories:
  redis-queue:
    image: redis:6
    host: 159.203.102.25
    port: 6379
    directories:
      - data:/data
    cmd:
      redis-server --save 60 1 --loglevel warning --maxmemory-policy noeviction --maxmemory 384mb --protected-mode no --port 6379

  redis-cache:
    image: redis:6
    host: 159.203.102.25
    port: 6380
    directories:
      - data:/data
    cmd:
      redis-server --save 60 1 --loglevel warning --maxmemory-policy allkeys-lru --maxmemory 384mb --protected-mode no --port 6380

traefik:
  options:
    publish:
      - "443:443"
  args:
    entryPoints.web.address: ":80"
    entryPoints.websecure.address: ":443"
    # volume:
    #   - "/letsencrypt/acme.json:/letsencrypt/acme.json"
    # entryPoints.web.http.redirections.entryPoint.to: websecure
    # entryPoints.web.http.redirections.entryPoint.scheme: https
    # entryPoints.web.http.redirections.entrypoint.permanent: true
    # certificatesResolvers.letsencrypt.acme.email: "rob@loomio.org"
    # certificatesResolvers.letsencrypt.acme.storage: "/letsencrypt/acme.json"
    # certificatesResolvers.letsencrypt.acme.httpchallenge: true
    # certificatesResolvers.letsencrypt.acme.httpchallenge.entrypoint: web 
