service: loomio
image: loomio/loomio_com
builder:
  args:
    LOOMIOCOM: 1
  multiarch: false

servers:
  web:
    - 165.227.76.125
  job:
    hosts:
      - 159.89.42.168
    cmd: bundle exec sidekiq    

  # cron:
  #   hosts:
  #     - 159.89.42.168
  #   cmd:
  #     bash -c "cat config/crontab | crontab - && cron -f"

registry:
  server: ghcr.io
  username: robguthrie
  password:
    - GH_PAT

env:
  secret:
    - AWS_ACCESS_KEY_ID
    - AWS_SECRET_ACCESS_KEY
    - CHARGIFY_API_KEY
    - CHARGIFY_APP_NAME
    - CHARGIFY_SITE_KEY
    - DATABASE_URL
    - DEVISE_SECRET
    - GOOGLE_APP_KEY
    - GOOGLE_APP_SECRET
    - GOOGLE_CLOUD_KEY
    - REDIS_CACHE_URL
    - REDIS_QUEUE_URL
    - RECAPTCHA_APP_KEY
    - RECAPTCHA_SECRET_KEY
    - SECRET_COOKIE_TOKEN
    - SECRET_KEY_BASE
    - SENTRY_PUBLIC_DSN
    - SMTP_PASSWORD
    - SMTP_USERNAME
    - TRANSLATE_CREDENTIALS

  clear:
    ALLOW_ROBOTS: 1
    AWS_BUCKET: loomio-uploads
    AWS_REGION: us-east-1
    CANONICAL_HOST: www.loomio.xyz
    CHANNELS_URI: 'wss://channels.loomio.xyz'
    ERROR_PAGE_URL: 'https://help.loomio.com/en/error'
    MAINTENANCE_PAGE_URL: 'https://help.loomio.com/en/maintenance'
    EXPLORE_MIN_MEMBERS: 4
    EXPLORE_MIN_THREADS: 2
    EXPLORE_REQUIRE_SUBSCRIPTION: 1
    FB_APP_ID_META: 457851034283863
    FEATURES_DEMO_GROUPS: 1
    FEATURES_SHOW_CONTACT: 1
    FEATURES_SHOW_CONTACT_CONSENT: 1
    FEATURES_SUBSCRIPTIONS: 1
    FEATURES_TRIALS: 1
    GOOGLE_SITE_VERIFICATION: VBjE1ew0T5SvIIaVInuq-fkL4DkBKt3yVm0rptVREhc
    HELPER_BOT_EMAIL: 'contact@loomio.com'
    MALLOC_ARENA_MAX: 2
    MAX_PENDING_INVITATIONS: 10000
    MAX_THREADS: 30
    MIN_THREADS: 30
    NEWSLETTER_ENABLED: 1
    OLD_REPLY_HOSTNAME: reply.loomio.org
    PAID_INVITATIONS_RATE_LIMIT: 50000
    # PLAUSABLE_SITE: 'loomio.org,all.loomio.com'
    # PLAUSABLE_SRC: 'https://measure.loomio.com/js/script.js'
    # PLAUSIBLE_SITE: 'loomio.org,all.loomio.com'
    # PLAUSIBLE_SRC: 'https://measure.loomio.com/js/script.js'
    PRIVACY_URL: 'https://help.loomio.com/en/policy/privacy'
    PUMA_WORKERS: 12
    RACK_ATTACK_RATE_MULTPLIER: 3
    RACK_TIMEOUT_SERVICE_TIMEOUT: 40
    RAILS_ENV: production
    RAILS_LOG_LEVEL: info
    REDIRECT_TO_CANONICAL_HOST: 1
    REPLY_HOSTNAME: reply.loomio.xyz
    SENTRY_SAMPLE_RATE: 0.1
    SMTP_AUTH: plain
    SMTP_DOMAIN: loomio.com
    SMTP_PORT: 587
    SMTP_SERVER: email-smtp.us-east-1.amazonaws.com
    SPAM_REGEX: '(flipssl\\.com|zoofood\\.org|w3boats\\.com|revutap\\.com|slowimo\\.com|relumyx\\.com|fineoak\\.org|diide\\.com|gusronk\\.com|appnox\\.com|akxpert\\.com|patmui\\.com|xhypm\\.com|5y5u\\.com|boldhut\\.com|botfed\\.com|fineloans\\.org|netjook\\.com|aramidth\\.com|kindbest\\.com|bsmitao\\.com|astarmax\\.com|irahada\\.com|naymeo\\.com|ichkoch\\.com|onzmail\\.com|seacob\\.com|fineloans\\.org|bombaya\\.com|astarmax\\.com|asfalio\\.com|wifimaple\\.com|whyflkj\\.com|ddwfzp\\.com|sejkt\\.com)'
    SUPPORT_EMAIL: 'contact@loomio.com'
    TERMS_URL: 'https://help.loomio.com/en/policy/terms'
    TRIAL_DAYS: 7
    TRIAL_INVITATIONS_RATE_LIMIT: 150
    USE_RACK_ATTACK: 1



accessories:
  # websockets:
  #   image: loomio/loomio_channel_server
  #   host: 165.22.32.232
  #   env:
  #     APP_URL: https://www.loomiotest.org

  # redis-cache:
  #   image: redis:5.0
  #   host: 10.132.53.193
  #   port: 6379
  #   directories:
  #     - data:/data
  #   cmd:
  #     redis-server --save 60 1 --loglevel warning --maxmemory-policy allkeys-lru --maxmemory 512mb --protected-mode no

  # redis-queue:
  #   image: redis:5.0
  #   host: 104.236.65.131
  #   port: 6379
  #   directories:
  #     - data:/data
  #   cmd:
  #     redis-server --save 60 1 --loglevel warning --maxmemory-policy allkeys-lru --maxmemory 512mb --protected-mode no

# Configure custom arguments for Traefik
# traefik:
#   args:
#     accesslog: true
#     accesslog.format: json
