default:
  - slight_smile
  - heart
  - laughing
  - clap
  - hugging
  - sunglasses
  - nerd
  - thinking
  - relieved
  - astonished
  - slight_frown
  - confused
  - disappointed
  - angry
  - cry
  - fingers_crossed
  - raised_hands
  - pray
  - ok_hand
  - wave
