loomio_i18n:
  selectable_locales: [ en, ar, an, be-BY, bg-BG, ca, cs, zh-TW, da, de, eo, es, el, fr, ga-IE, id, it, he, hu, ja, ko, ml, nl-NL, pl, pt-BR, ro, sr, sr-RS, sk, sl, sv, vi, tr, uk ]
  additional_detectable_locales: [ be, pt, zh, zh-HK ]

  fallbacks:
    an:      es
    be:      be-BY
    ca:      es
    'pt-PT': pt-BR
    pt:      pt-BR
    zh:      zh-TW
    'zh-HK': zh-TW

  # for locales which are only serving as redirects, make sure to add to  :
  #   i) additional_detectable_locales
  #  ii) fallbacks
  # iii) a dummy yaml e.g. config/locales/fallback.zh-HK.yml

  #right_to_left_locales
  rtl_locales: [ ar, he, fa-IR, ur, ur-PK ]

  # only for display purposes, please don't depend on this in the system
  test_locales: [ cmn, hi, hr, fi, gl, it-CH, km, lv, mk, mi, fa-IR, pt-PT, ru, te, ur, ur-PK ]
