count:
  prevent_anonymous: true
  material_icon: mdi-human-greeting-variant
  vote_method: show_thumbs
  validate_minimum_stance_choices: true
  validate_maximum_stance_choices: true
  validate_dots_per_person: true
  has_option_icon: true
  per_option_reason_prompt: true
  order_results_by: priority
  options_have_meaning: true
  common_poll_options:
    - key: accept
      name_i18n: poll_count_options.accept
      icon: agree
      meaning_i18n: poll_count_vote_form.accept_meaning
      prompt_i18n: poll_count_vote_form.accept_prompt
      color: '#70C9F8'
      default: true
    - key: decline
      name_i18n: poll_count_options.decline
      icon: disagree
      meaning_i18n: poll_count_vote_form.decline_meaning
      prompt_i18n: poll_count_vote_form.decline_prompt
      color: "#C8E56E"
      default: true
  defaults:
    poll_option_name_format: 'plain'
    process_name_i18n: decision_tools_card.count_title
    process_subtitle_i18n: poll_count_form.tool_tip_collapsed
    chart_type: bar
    min_score: 1
    max_score: 1
    minimum_stance_choices: 1
    maximum_stance_choices: 1
    agree_target: 5
    dots_per_person: 1
    default_duration_in_days: 3

check:
  material_icon: mdi-head-question
  vote_method: show_thumbs
  validate_minimum_stance_choices: true
  validate_maximum_stance_choices: true
  validate_dots_per_person: true
  has_option_icon: true
  per_option_reason_prompt: true
  order_results_by: priority
  options_have_meaning: true
  common_poll_options:
    - key: looks_good
      name_i18n: poll_check_options.looks_good
      icon: agree
      meaning_i18n: poll_check_options.looks_good_meaning
      prompt_i18n: poll_check_options.looks_good_prompt
      color: '#70C9F8'
      default: true
    - key: not_sure
      name_i18n: poll_check_options.not_sure
      icon: abstain
      meaning_i18n: poll_check_options.not_sure_meaning
      prompt_i18n: poll_check_options.not_sure_prompt
      color: '#70C9F8'
      default: true
    - key: concerned
      name_i18n: poll_check_options.concerned
      icon: disagree
      meaning_i18n: poll_check_options.concerned_meaning
      prompt_i18n: poll_check_options.concerned_prompt
      color: "#C8E56E"
      default: true
  defaults:
    poll_option_name_format: 'plain'
    process_name_i18n: decision_tools_card.check_title
    process_subtitle_i18n: poll_check_options.check_subtitle
    chart_type: pie
    min_score: 1
    max_score: 1
    minimum_stance_choices: 1
    maximum_stance_choices: 1
    agree_target: 5
    dots_per_person: 1
    default_duration_in_days: 3

proposal:
  material_icon: mdi-thumbs-up-down
  vote_method: show_thumbs
  vote_method_hint_i18n: poll_common_form.voting_methods.show_thumbs_hint
  validate_minimum_stance_choices: true
  validate_dots_per_person: true
  has_option_icon: true
  per_option_reason_prompt: true
  chart_column: score_percent
  order_results_by: priority
  options_have_meaning: true
  common_poll_options:
    - key: agree
      name_i18n: poll_proposal_options.agree
      icon: agree
      meaning_i18n: poll_proposal_options.agree_meaning
      prompt_i18n: poll_proposal_vote_form.agree_reason_placeholder
      color: '#70C9F8'
      default: true
    - key: abstain
      name_i18n: poll_proposal_options.abstain
      icon: abstain
      meaning_i18n: poll_proposal_options.abstain_meaning
      prompt_i18n: poll_proposal_options.abstain_prompt
      color: "#C8E56E"
      default: true
    - key: disagree
      name_i18n: poll_proposal_options.disagree
      icon: disagree
      meaning_i18n: poll_proposal_options.disagree_meaning
      prompt_i18n: poll_proposal_vote_form.disagree_reason_placeholder
      color: "#D38FE1"
      default: true
    - key: block
      name_i18n: poll_proposal_options.block
      icon: block
      meaning_i18n: poll_proposal_options.block_meaning
      prompt_i18n: poll_proposal_vote_form.block_reason_placeholder
      color: "#999FDE"
    - key: consent
      name_i18n: poll_proposal_options.consent
      icon: agree
      meaning_i18n: poll_proposal_options.consent_meaning
      prompt_i18n: poll_proposal_options.consent_prompt
      color: "#70C9F8"
    - key: objection
      name_i18n: poll_proposal_options.objection
      icon: disagree
      meaning_i18n: poll_proposal_options.objection_meaning
      prompt_i18n: poll_proposal_options.objection_prompt
      color: "#D38FE1"
    - key: object
      name_i18n: poll_proposal_options.object
      icon: disagree
      meaning_i18n: poll_proposal_options.objection_meaning
      prompt_i18n: poll_proposal_options.objection_prompt
      color: "#D38FE1"
  defaults:
    poll_option_name_format: plain
    process_name_i18n: decision_tools_card.proposal_title
    process_subtitle_i18n: poll_proposal_form.tool_tip_collapsed
    chart_type: pie
    min_score: 1
    max_score: 1
    minimum_stance_choices: 1
    maximum_stance_choices: 1
    dots_per_person: 1
    default_duration_in_days: 7

meeting:
  material_icon: mdi-calendar-multiselect
  prevent_anonymous: true
  vote_method: time_poll
  vote_method_hint_i18n: poll_common_form.voting_methods.time_poll_hint
  require_all_choices: true
  validate_min_score: true
  validate_max_score: true
  order_results_by: priority
  options_have_meaning: false
  defaults:
    meeting_duration: 60
    poll_option_name_format: iso8601
    process_name_i18n: decision_tools_card.meeting_title
    process_subtitle_i18n: poll_meeting_form.tool_tip_collapsed
    chart_type: grid
    min_score: 0
    max_score: 2
    default_duration_in_days: 3
    can_respond_maybe: true

poll:
  material_icon: mdi-check
  vote_method: choose
  vote_method_hint_i18n: poll_common_form.voting_methods.choose_hint
  can_shuffle_options: true
  validate_minimum_stance_choices: true
  validate_maximum_stance_choices: true
  validate_min_score: true
  validate_max_score: true
  chart_column: max_score_percent
  order_results_by: total_score_desc
  options_have_meaning: true
  defaults:
    poll_option_name_format: plain
    process_name_i18n: poll_common_form.voting_methods.simple_poll
    process_subtitle_i18n: poll_poll_form.tool_tip_collapsed
    chart_type: bar
    min_score: 1
    max_score: 1
    minimum_stance_choices: 1
    maximum_stance_choices: 1
    default_duration_in_days: 3

dot_vote:
  material_icon: mdi-chart-bar-stacked
  vote_method: allocate
  vote_method_hint_i18n: poll_common_form.voting_methods.allocate_hint
  can_shuffle_options: true
  validate_min_score: true
  validate_dots_per_person: true
  order_results_by: total_score_desc
  options_have_meaning: true
  defaults:
    poll_option_name_format: plain
    process_name_i18n: decision_tools_card.dot_vote_title
    process_subtitle_i18n: poll_dot_vote_form.tool_tip_collapsed
    chart_type: bar
    dots_per_person: 8
    min_score: 0
    minimum_stance_choices: 0
    default_duration_in_days: 3

score:
  material_icon: mdi-chart-gantt
  vote_method: score
  vote_method_hint_i18n: poll_common_form.voting_methods.score_hint
  can_shuffle_options: true
  validate_min_score: true
  validate_max_score: true
  order_results_by: total_score_desc
  options_have_meaning: true
  defaults:
    poll_option_name_format: plain
    process_name_i18n: decision_tools_card.score_title
    process_subtitle_i18n: poll_score_form.tool_tip_collapsed
    chart_type: bar
    min_score: 1
    max_score: 5
    minimum_stance_choices: 1
    default_duration_in_days: 3

ranked_choice:
  material_icon: mdi-format-list-numbered
  vote_method: ranked_choice
  vote_method_hint_i18n: poll_common_form.voting_methods.ranked_choice_hint
  can_shuffle_options: true
  validate_minimum_stance_choices: true
  require_all_choices: true
  validate_min_score: true
  order_results_by: total_score_desc
  options_have_meaning: true
  defaults:
    poll_option_name_format: plain
    process_name_i18n: decision_tools_card.ranked_choice_title
    process_subtitle_i18n: poll_ranked_choice_form.tool_tip_collapsed
    chart_type: bar
    minimum_stance_choices: 2
    min_score: 1
    default_duration_in_days: 3

