# for providers which provide OAuth login capability
identity:
  - google
  - facebook
  - slack
  - microsoft
  - saml

# for providers which provide additional API access
community:
  - facebook
  - slack
