Spring.watch(
  ".ruby-version",
  ".miserc.toml",
  "mise.toml",
  "mise.development.toml",
  "mise.test.toml",
  ".env.development",
  ".env.development.local",
  "tmp/restart.txt",
  "tmp/caching-dev.txt"
)
