- name: (GMT -12:00) Eniwetok, Kwajalein
  value: Pacific/Tarawa
- name: (GMT -11:00) Midway Island, Samoa
  value: Pacific/Midway
- name: (GMT -10:00) Hawaii
  value: Pacific/Honolulu
- name: (GMT -9:00) Alaska
  value: America/Juneau
- name: (GMT -8:00) Pacific Time (US & Canada)
  value: America/Los_Angeles
- name: (GMT -7:00) Mountain Time (US & Canada)
  value: America/Phoenix
- name: (GMT -6:00) Central Time (US & Canada), Mexico City
  value: America/Chicago
- name: (GMT -5:00) Eastern Time (US & Canada), Bogota, Lima
  value: America/New_York
- name: (GMT -4:00) Atlantic Time (Canada), Caracas, La Paz
  value: Atlantic/Bermuda
- name: (GMT -3:30) Newfoundland
  value: America/St_Johns
- name: (GMT -3:00) Brazil, Buenos Aires, Georgetown
  value: America/Buenos_Aires
- name: (GMT -2:00) Mid-Atlantic
  value: America/Noronha
- name: (GMT -1:00 hour) Azores, Cape Verde Islands
  value: Atlantic/Azores
- name: (GMT) Western Europe Time, London, Lisbon, Casablanca
  value: Europe/London
- name: (GMT +1:00 hour) Brussels, Copenhagen, Madrid, Paris
  value: Europe/Paris
- name: (GMT +2:00) Kaliningrad, South Africa
  value: Europe/Kaliningrad
- name: (GMT +3:00) Baghdad, Riyadh, Moscow, St. Petersburg
  value: Asia/Baghdad
- name: (GMT +3:30) Tehran
  value: Asia/Tehran
- name: (GMT +4:00) Abu Dhabi, Muscat, Baku, Tbilisi
  value: Asia/Dubai
- name: (GMT +4:30) Kabul
  value: Asia/Kabul
- name: (GMT +5:00) Ekaterinburg, Islamabad, Karachi, Tashkent
  value: Asia/Yekaterinburg
- name: (GMT +5:30) Bombay, Calcutta, Madras, New Delhi
  value: Asia/Kolkata
- name: (GMT +5:45) Kathmandu
  value: Asia/Katmandu
- name: (GMT +6:00) Almaty, Dhaka, Colombo
  value: Asia/Almaty
- name: (GMT +7:00) Bangkok, Hanoi, Jakarta
  value: Asia/Bangkok
- name: (GMT +8:00) Beijing, Perth, Singapore, Hong Kong
  value: Asia/Shanghai
- name: (GMT +9:00) Tokyo, Seoul, Osaka, Sapporo, Yakutsk
  value: Asia/Tokyo
- name: (GMT +9:30) Adelaide, Darwin
  value: Australia/Adelaide
- name: (GMT +10:00) Eastern Australia, Guam, Vladivostok
  value: Australia/Hobart
- name: (GMT +11:00) Magadan, Solomon Islands, New Caledonia
  value: Pacific/Ponape
- name: (GMT +12:00) Auckland, Wellington, Fiji, Kamchatka
  value: Pacific/Auckland
