import RecordStore from '@/record_store/record_store';
import AppConfig   from '@/services/app_config';
import loki from 'lokijs'

import CommentRecordsInterface from '@/interfaces/comment_records_interface';
import ChatbotRecordsInterface from '@/interfaces/chatbot_records_interface';
import DiscussionRecordsInterface from '@/interfaces/discussion_records_interface';
import DiscussionTemplateRecordsInterface from '@/interfaces/discussion_template_records_interface';
import DiscussionReaderRecordsInterface from '@/interfaces/discussion_reader_records_interface';
import EventRecordsInterface from '@/interfaces/event_records_interface';
import GroupRecordsInterface from '@/interfaces/group_records_interface';
import MembershipRecordsInterface from '@/interfaces/membership_records_interface';
import MembershipRequestRecordsInterface from '@/interfaces/membership_request_records_interface';
import NotificationRecordsInterface from '@/interfaces/notification_records_interface';
import UserRecordsInterface from '@/interfaces/user_records_interface';
import VersionRecordsInterface from '@/interfaces/version_records_interface';
import TranslationRecordsInterface from '@/interfaces/translation_records_interface';
import SessionRecordsInterface from '@/interfaces/session_records_interface';
import RegistrationRecordsInterface from '@/interfaces/registration_records_interface';
import PollRecordsInterface from '@/interfaces/poll_records_interface';
import PollTemplateRecordsInterface from '@/interfaces/poll_template_records_interface';
import PollOptionRecordsInterface from '@/interfaces/poll_option_records_interface';
import StanceRecordsInterface from '@/interfaces/stance_records_interface';
import OutcomeRecordsInterface from '@/interfaces/outcome_records_interface';
import ContactMessageRecordsInterface from '@/interfaces/contact_message_records_interface';
import ReactionRecordsInterface from '@/interfaces/reaction_records_interface';
import ContactRequestRecordsInterface from '@/interfaces/contact_request_records_interface';
import DocumentRecordsInterface from '@/interfaces/document_records_interface';
import AttachmentRecordsInterface from '@/interfaces/attachment_records_interface';
import LoginTokenRecordsInterface from '@/interfaces/login_token_records_interface';
import MessageChannelRecordsInterface from '@/interfaces/message_channel_records_interface';
import TagRecordsInterface from '@/interfaces/tag_records_interface';
import TaskRecordsInterface from '@/interfaces/task_records_interface';
import WebhookRecordsInterface from '@/interfaces/webhook_records_interface';

const db      = new loki('default.db');
const records = new RecordStore(db);

records.addRecordsInterface(CommentRecordsInterface);
records.addRecordsInterface(ChatbotRecordsInterface);
records.addRecordsInterface(DiscussionRecordsInterface);
records.addRecordsInterface(DiscussionTemplateRecordsInterface);
records.addRecordsInterface(DiscussionReaderRecordsInterface);
records.addRecordsInterface(EventRecordsInterface);
records.addRecordsInterface(GroupRecordsInterface);
records.addRecordsInterface(MembershipRecordsInterface);
records.addRecordsInterface(MembershipRequestRecordsInterface);
records.addRecordsInterface(NotificationRecordsInterface);
records.addRecordsInterface(UserRecordsInterface);
records.addRecordsInterface(VersionRecordsInterface);
records.addRecordsInterface(TranslationRecordsInterface);
records.addRecordsInterface(SessionRecordsInterface);
records.addRecordsInterface(RegistrationRecordsInterface);
records.addRecordsInterface(PollRecordsInterface);
records.addRecordsInterface(PollTemplateRecordsInterface);
records.addRecordsInterface(PollOptionRecordsInterface);
records.addRecordsInterface(StanceRecordsInterface);
records.addRecordsInterface(OutcomeRecordsInterface);
records.addRecordsInterface(ContactMessageRecordsInterface);
records.addRecordsInterface(ReactionRecordsInterface);
records.addRecordsInterface(ContactRequestRecordsInterface);
records.addRecordsInterface(DocumentRecordsInterface);
records.addRecordsInterface(AttachmentRecordsInterface);
records.addRecordsInterface(LoginTokenRecordsInterface);
records.addRecordsInterface(MessageChannelRecordsInterface);
records.addRecordsInterface(TagRecordsInterface);
records.addRecordsInterface(TaskRecordsInterface);
records.addRecordsInterface(WebhookRecordsInterface);

AppConfig.records = records;
export default records;
