name: Publish Loomio.com image

on:
  # push: master
  push:

jobs:
  push_to_registry:
    name: Build and push loomio.com image
    runs-on: ubuntu-latest
    env:
      GH_PAT: ${{ secrets.GH_PAT }}
    steps:
      - name: Check out loomio source
        uses: actions/checkout@v3

      - name: Check out loomio_subs engine
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_PAT }}
          repository: loomio/loomio_subs
          path: engines
          ref: main

      - name: Check out loomio-website gem
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_PAT }}
          repository: loomio/loomio-website
          path: website
          ref: main

      - name: build website
        run: |
          cd website
          npm install
          npm run build
          cd ..
          cp -R ./website/_site/* ./public/
          rm -rf ./website

      - name: build docker image
        run: |
          echo $GH_PAT | docker login ghcr.io -u robguthrie --password-stdin
          docker build . -t ghcr.io/loomio/loomio_com:latest
          docker push ghcr.io/loomio/loomio_com:latest
